// src/repositories/checklistRepository.ts
// CRUD helpers for piling_daily_checklists, piling_checklist_piles,
// piling_checklist_personnel in local SQLite.

import { eq, and } from 'drizzle-orm';
import { initDb } from '@db/client';
import {
  pilingDailyChecklists,
  pilingChecklistPiles,
  pilingChecklistPersonnel,
  pilePlanSteps,
  pileActualSteps,
  type PilingDailyChecklist,
  type NewPilingDailyChecklist,
  type PilingChecklistPile,
  type NewPilingChecklistPile,
  type PilingChecklistPersonnel,
  type NewPilingChecklistPersonnel,
  type PilePlanStep,
  type PileActualStep,
} from '@db/schema';

// ─── Daily Checklists ─────────────────────────────────────────────────────────

/**
 * Get a checklist by its primary key.
 */
export async function getChecklistById(
  id: string,
): Promise<PilingDailyChecklist | undefined> {
  const db = await initDb();
  const rows = await db
    .select()
    .from(pilingDailyChecklists)
    .where(eq(pilingDailyChecklists.id, id))
    .limit(1);
  return rows[0];
}

/**
 * Get a checklist by site + date ("YYYY-MM-DD").
 * Returns undefined if no checklist exists for that day.
 */
export async function getChecklistByDate(
  siteId: string,
  date: string,
): Promise<PilingDailyChecklist | undefined> {
  const db = await initDb();
  const rows = await db
    .select()
    .from(pilingDailyChecklists)
    .where(
      and(
        eq(pilingDailyChecklists.siteId, siteId),
        eq(pilingDailyChecklists.date, date),
      ),
    )
    .limit(1);
  return rows[0];
}

/**
 * Get all checklists for a site, most recent first.
 */
export async function getChecklistsBySite(
  siteId: string,
): Promise<PilingDailyChecklist[]> {
  const db = await initDb();
  return db
    .select()
    .from(pilingDailyChecklists)
    .where(eq(pilingDailyChecklists.siteId, siteId))
    .orderBy(pilingDailyChecklists.date)
    .all();
}

/**
 * Insert a new checklist row. The caller is responsible for generating the id.
 */
export async function insertChecklist(
  checklist: NewPilingDailyChecklist,
): Promise<void> {
  const db = await initDb();
  await db.insert(pilingDailyChecklists).values(checklist);
}

/**
 * Update mutable fields on an existing checklist (status, supervisor, notes, times).
 */
export async function updateChecklist(
  id: string,
  patch: Partial<Pick<
    PilingDailyChecklist,
    'shiftTypeId' | 'planStartTime' | 'planEndTime' | 'supervisorId' | 'supervisorId2' | 'notes' | 'status' | 'updatedAt'
  >>,
): Promise<void> {
  const db = await initDb();
  await db
    .update(pilingDailyChecklists)
    .set({ ...patch, updatedAt: Date.now() })
    .where(eq(pilingDailyChecklists.id, id));
}

// ─── Checklist Piles ──────────────────────────────────────────────────────────

/**
 * Get all checklist-pile entries for a given checklist, ordered by seq_no.
 */
export async function getChecklistPiles(
  checklistId: string,
): Promise<PilingChecklistPile[]> {
  const db = await initDb();
  return db
    .select()
    .from(pilingChecklistPiles)
    .where(eq(pilingChecklistPiles.checklistId, checklistId))
    .orderBy(pilingChecklistPiles.seqNo)
    .all();
}

/**
 * Insert a batch of checklist-pile entries.
 * Each entry must have a unique id generated by the caller.
 */
export async function insertChecklistPiles(
  entries: NewPilingChecklistPile[],
): Promise<void> {
  if (!entries.length) return;
  const db = await initDb();
  for (const entry of entries) {
    await db
      .insert(pilingChecklistPiles)
      .values(entry)
      .onConflictDoNothing();
  }
}

/**
 * Update the status of a single checklist-pile entry.
 */
export async function updateChecklistPileStatus(
  id: string,
  status: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED',
): Promise<void> {
  const db = await initDb();
  await db
    .update(pilingChecklistPiles)
    .set({ status })
    .where(eq(pilingChecklistPiles.id, id));
}

/**
 * Delete all checklist-pile entries for a checklist.
 * Used when regenerating a plan from scratch.
 */
export async function deleteChecklistPiles(checklistId: string): Promise<void> {
  const db = await initDb();
  await db
    .delete(pilingChecklistPiles)
    .where(eq(pilingChecklistPiles.checklistId, checklistId));
}

// ─── Checklist Personnel ──────────────────────────────────────────────────────

/**
 * Replace all personnel assignments for a checklist day.
 */
export async function setChecklistPersonnel(
  checklistId: string,
  entries: NewPilingChecklistPersonnel[],
): Promise<void> {
  const db = await initDb();
  await db
    .delete(pilingChecklistPersonnel)
    .where(eq(pilingChecklistPersonnel.checklistId, checklistId));
  if (entries.length) {
    await db.insert(pilingChecklistPersonnel).values(entries);
  }
}

/**
 * Get all personnel ids assigned to a checklist.
 */
export async function getChecklistPersonnelIds(
  checklistId: string,
): Promise<string[]> {
  const db = await initDb();
  const rows = await db
    .select({ personnelId: pilingChecklistPersonnel.personnelId })
    .from(pilingChecklistPersonnel)
    .where(eq(pilingChecklistPersonnel.checklistId, checklistId))
    .all();
  return rows.map((r) => r.personnelId);
}
