// src/repositories/checklistRepository.ts
// CRUD helpers for piling_daily_checklists, piling_checklist_piles,
// piling_checklist_personnel in local SQLite.

import { eq, and, inArray } from 'drizzle-orm';
import { initDb } from '@db/client';
import {
  pilingDailyChecklists,
  pilingChecklistPiles,
  pilingChecklistPersonnel,
  pilePlanSteps,
  pileActualSteps,
  type PilingDailyChecklist,
  type NewPilingDailyChecklist,
  type PilingChecklistPile,
  type NewPilingChecklistPile,
  type PilingChecklistPersonnel,
  type NewPilingChecklistPersonnel,
  type PileActualStep,
  type NewPilePlanStep,
  type NewPileActualStep,
} from '@db/schema';
import { generateId, isContinuingStep } from '@utils/helpers';

/** A plain db handle, or the transaction-scoped one passed into
 * db.transaction(async (tx) => {...}) — a distinct type from the plain
 * handle (no $client property), but structurally fine for the query-builder
 * calls used here. */
type Db = Awaited<ReturnType<typeof initDb>>;
type Tx = Parameters<Parameters<Db['transaction']>[0]>[0];

// ─── Daily Checklists ─────────────────────────────────────────────────────────

/**
 * Get a checklist by its primary key.
 */
export async function getChecklistById(
  id: string,
): Promise<PilingDailyChecklist | undefined> {
  const db = await initDb();
  const rows = await db
    .select()
    .from(pilingDailyChecklists)
    .where(eq(pilingDailyChecklists.id, id))
    .limit(1);
  return rows[0];
}

/**
 * Get a checklist by site + date ("YYYY-MM-DD").
 * Returns undefined if no checklist exists for that day.
 */
export async function getChecklistByDate(
  siteId: string,
  date: string,
): Promise<PilingDailyChecklist | undefined> {
  const db = await initDb();
  const rows = await db
    .select()
    .from(pilingDailyChecklists)
    .where(
      and(
        eq(pilingDailyChecklists.siteId, siteId),
        eq(pilingDailyChecklists.date, date),
      ),
    )
    .limit(1);
  return rows[0];
}

/**
 * Get all checklists for a site, most recent first.
 */
export async function getChecklistsBySite(
  siteId: string,
): Promise<PilingDailyChecklist[]> {
  const db = await initDb();
  return db
    .select()
    .from(pilingDailyChecklists)
    .where(eq(pilingDailyChecklists.siteId, siteId))
    .orderBy(pilingDailyChecklists.date)
    .all();
}

/**
 * Insert a new checklist row. The caller is responsible for generating the id.
 */
export async function insertChecklist(
  checklist: NewPilingDailyChecklist,
): Promise<void> {
  const db = await initDb();
  await db.insert(pilingDailyChecklists).values(checklist);
}

/**
 * Update mutable fields on an existing checklist (status, supervisor, notes, times).
 */
export async function updateChecklist(
  id: string,
  patch: Partial<Pick<
    PilingDailyChecklist,
    'shiftTypeId' | 'planStartTime' | 'planEndTime' | 'notes' | 'status' | 'updatedAt'
  >>,
): Promise<void> {
  const db = await initDb();
  await db
    .update(pilingDailyChecklists)
    .set({ ...patch, updatedAt: Date.now() })
    .where(eq(pilingDailyChecklists.id, id));
}

// ─── Checklist Piles ──────────────────────────────────────────────────────────

/**
 * Get all checklist-pile entries for a given checklist, ordered by seq_no.
 */
export async function getChecklistPiles(
  checklistId: string,
): Promise<PilingChecklistPile[]> {
  const db = await initDb();
  return db
    .select()
    .from(pilingChecklistPiles)
    .where(eq(pilingChecklistPiles.checklistId, checklistId))
    .orderBy(pilingChecklistPiles.seqNo)
    .all();
}

/**
 * Insert a batch of checklist-pile entries.
 * Each entry must have a unique id generated by the caller.
 */
export async function insertChecklistPiles(
  entries: NewPilingChecklistPile[],
): Promise<void> {
  if (!entries.length) return;
  const db = await initDb();
  for (const entry of entries) {
    await db
      .insert(pilingChecklistPiles)
      .values(entry)
      .onConflictDoNothing();
  }
}

/**
 * Update the status of a single checklist-pile entry.
 */
export async function updateChecklistPileStatus(
  id: string,
  status: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED',
): Promise<void> {
  const db = await initDb();
  await db
    .update(pilingChecklistPiles)
    .set({ status })
    .where(eq(pilingChecklistPiles.id, id));
}

/**
 * Delete all checklist-pile entries for a checklist.
 * Used when regenerating a plan from scratch.
 */
export async function deleteChecklistPiles(checklistId: string): Promise<void> {
  const db = await initDb();
  await db
    .delete(pilingChecklistPiles)
    .where(eq(pilingChecklistPiles.checklistId, checklistId));
}

// ─── Checklist Pile Timings (planned vs actual span, for progress calc) ──────

export type PileTiming = {
  checklistPileId: string;
  status: PilingChecklistPile['status'];
  plannedStart: string | null; // earliest pile_plan_steps.planned_start for this pile
  plannedEnd: string | null;   // latest pile_plan_steps.planned_end for this pile
  actualStart: string | null;  // earliest pile_actual_steps.actual_start for this pile
  actualEnd: string | null;    // latest pile_actual_steps.actual_end, only once status is COMPLETED
};

/**
 * For each pile on this checklist, collapse its plan steps into one planned
 * span (earliest plannedStart -> latest plannedEnd across rig/crane tracks)
 * and its actual steps into one actual span. Feed the result into
 * computeChecklistProgress() to get completion % and schedule variance.
 */
export async function getChecklistPileTimings(checklistId: string): Promise<PileTiming[]> {
  const piles = await getChecklistPiles(checklistId);
  if (!piles.length) return [];

  const db = await initDb();
  const pileIds = piles.map((p) => p.id);

  const planSteps = await db
    .select()
    .from(pilePlanSteps)
    .where(inArray(pilePlanSteps.checklistPileId, pileIds))
    .all();

  const actualSteps = await db
    .select()
    .from(pileActualSteps)
    .where(inArray(pileActualSteps.checklistPileId, pileIds))
    .all();

  return piles.map((pile): PileTiming => {
    const plans = planSteps.filter((s) => s.checklistPileId === pile.id);
    const actuals = actualSteps.filter((s) => s.checklistPileId === pile.id);
    const started = actuals.filter((s): s is PileActualStep & { actualStart: string } => !!s.actualStart);
    const finished = actuals.filter((s): s is PileActualStep & { actualEnd: string } => !!s.actualEnd);

    return {
      checklistPileId: pile.id,
      status: pile.status as PileTiming['status'],
      plannedStart: plans.length
        ? plans.reduce((min, s) => (s.plannedStart < min ? s.plannedStart : min), plans[0].plannedStart)
        : null,
      // If any step is "continuing" (null plannedEnd), the pile itself is
      // continuing — null, not silently truncated to its second-to-last step's end.
      plannedEnd: plans.length && !plans.some(isContinuingStep)
        ? plans.reduce((max, s) => (s.plannedEnd! > max ? s.plannedEnd! : max), plans[0].plannedEnd!)
        : null,
      actualStart: started.length
        ? started.reduce((min, s) => (s.actualStart < min ? s.actualStart : min), started[0].actualStart)
        : null,
      actualEnd: pile.status === 'COMPLETED' && finished.length
        ? finished.reduce((max, s) => (s.actualEnd > max ? s.actualEnd : max), finished[0].actualEnd)
        : null,
    };
  });
}

// ─── Server hydration (server-owned plans — see plan_generation_service.py) ──

/**
 * Writes the server's full `ChecklistOut` response (raw snake_case JSON, as
 * returned by POST /plans/generate, GET /checklists/{id}, or GET
 * /piling/sites/{site}/plans/generate) into local SQLite as the authoritative
 * copy — checklist, checklist_piles, and their plan/actual steps are wholesale
 * replaced with what the server sent, never merged with whatever was there
 * before. This is the single hydration path shared by:
 *   - PlanContext.generatePlan() after the server creates/returns a plan
 *   - GeneratePlanCalendarSheet reconciling a plan that exists server-side
 *     but not yet in local SQLite (e.g. after a reinstall)
 *   - the syncActivePlan bootstrap step
 *
 */
export async function hydrateChecklistFromServer(serverChecklist: {
  id: string;
  site_id: string;
  date: string;
  shift_type_id: string | null;
  plan_start_time: string | null;
  plan_end_time: string | null;
  notes: string | null;
  status: string;
  checklist_personnel?: Array<{
    role: string;
    machine_id: string | null;
    shift_slot: number | null;
    personnel: { id: string };
  }>;
  checklist_piles?: Array<{
    id: string;
    seq_no: number;
    status: string;
    pile: { id: string };
    rig: { id: string };
    crane: { id: string };
    // The server's own updated_at — echoed back verbatim on the next push as
    // the optimistic-concurrency version (see pilingChecklistPiles.serverUpdatedAt).
    updated_at?: string | null;
    plan_steps?: Array<{
      id: string;
      step_id: string;
      planned_start: string;
      planned_end: string | null;
      duration_minutes: number | null;
      buffer_minutes: number | null;
      assigned_machine_id: string | null;
    }>;
    actual_steps?: Array<{
      id: string;
      step_id: string;
      actual_start: string | null;
      actual_end: string | null;
      remarks: string | null;
      // See checklist_piles[].updated_at above — same purpose, per actual step.
      updated_at?: string | null;
    }>;
  }>;
}): Promise<void> {
  const db = await initDb();
  const now = Date.now();

  const checklistPatch = {
    siteId: serverChecklist.site_id,
    date: serverChecklist.date,
    shiftTypeId: serverChecklist.shift_type_id,
    planStartTime: serverChecklist.plan_start_time,
    planEndTime: serverChecklist.plan_end_time,
    notes: serverChecklist.notes,
    status: serverChecklist.status,
  };

  const checklistId = serverChecklist.id;
  const serverPiles = serverChecklist.checklist_piles ?? [];

  // Everything below is one logical "replace this checklist's data with the
  // server's authoritative copy" operation — wrapped in a single transaction
  // (instead of ~8-20 separate autocommit statements) so it's atomic and
  // holds the write lock only once, not repeatedly, shrinking the window for
  // a concurrent writer (e.g. the background sync puller, which calls this
  // same function) to collide with it.
  await db.transaction(async (tx) => {
    await tx
      .insert(pilingDailyChecklists)
      .values({ id: serverChecklist.id, ...checklistPatch, createdAt: now, updatedAt: now })
      .onConflictDoUpdate({
        target: pilingDailyChecklists.id,
        set: { ...checklistPatch, updatedAt: now },
      });

    await setChecklistPersonnel(
      checklistId,
      (serverChecklist.checklist_personnel ?? []).map((cp) => ({
        id: generateId(),
        checklistId,
        personnelId: cp.personnel.id,
        role: cp.role,
        machineId: cp.machine_id,
        shiftSlot: cp.shift_slot,
      })),
      tx,
    );

    // Capture the *old* checklist-pile ids before replacing them — once
    // they're deleted below, any plan/actual step rows still referencing
    // them become orphaned (SQLite FKs aren't enforced here, so nothing
    // cascades). Must read this before the delete, not after, or it
    // captures the new ids instead of the stale ones that actually need
    // cleaning up.
    const staleCpIds = (
      await tx
        .select({ id: pilingChecklistPiles.id })
        .from(pilingChecklistPiles)
        .where(eq(pilingChecklistPiles.checklistId, checklistId))
        .all()
    ).map((r) => r.id);

    // Wholesale replace — the server response is the full authoritative set
    // for this checklist, not a delta.
    await tx.delete(pilingChecklistPiles).where(eq(pilingChecklistPiles.checklistId, checklistId));

    if (serverPiles.length) {
      await tx.insert(pilingChecklistPiles).values(
        serverPiles.map(
          (cp): NewPilingChecklistPile => ({
            id: cp.id,
            checklistId,
            pileId: cp.pile.id,
            seqNo: cp.seq_no,
            rigId: cp.rig.id,
            craneId: cp.crane.id,
            status: cp.status as NewPilingChecklistPile['status'],
            createdAt: now,
            serverUpdatedAt: cp.updated_at ?? null,
          }),
        ),
      );
    }

    const planStepRows: NewPilePlanStep[] = [];
    const actualStepRows: NewPileActualStep[] = [];
    for (const cp of serverPiles) {
      for (const ps of cp.plan_steps ?? []) {
        planStepRows.push({
          id: ps.id,
          checklistPileId: cp.id,
          stepId: ps.step_id,
          plannedStart: ps.planned_start,
          plannedEnd: ps.planned_end,
          durationMinutes: ps.duration_minutes,
          bufferMinutes: ps.buffer_minutes,
          assignedMachineId: ps.assigned_machine_id,
          createdAt: now,
        });
      }
      for (const as of cp.actual_steps ?? []) {
        actualStepRows.push({
          id: as.id,
          checklistPileId: cp.id,
          stepId: as.step_id,
          actualStart: as.actual_start,
          actualEnd: as.actual_end,
          remarks: as.remarks,
          createdAt: now,
          updatedAt: now,
          serverUpdatedAt: as.updated_at ?? null,
        });
      }
    }

    // deletePlanStepsForChecklist/deleteActualStepsForChecklist (planRepository)
    // aren't reusable here without a circular import — clean up using the
    // stale checklist-pile ids captured above, then insert the fresh set.
    for (const cpId of staleCpIds) {
      await tx.delete(pilePlanSteps).where(eq(pilePlanSteps.checklistPileId, cpId));
      await tx.delete(pileActualSteps).where(eq(pileActualSteps.checklistPileId, cpId));
    }

    if (planStepRows.length) await tx.insert(pilePlanSteps).values(planStepRows);
    if (actualStepRows.length) await tx.insert(pileActualSteps).values(actualStepRows);
  });
}

/**
 * Hard-delete locally cached checklist-piles the server has soft-deleted
 * (Phase 3 delta pull's `deleted_checklist_pile_ids`), plus their plan/actual
 * steps — the same cleanup hydrateChecklistFromServer already does for stale
 * checklist-pile ids, reused here for ids the server explicitly reports as
 * gone rather than ones this function's own wholesale-replace discovered.
 */
export async function purgeChecklistPilesByIds(checklistPileIds: string[]): Promise<void> {
  if (!checklistPileIds.length) return;
  const db = await initDb();
  await db.delete(pilePlanSteps).where(inArray(pilePlanSteps.checklistPileId, checklistPileIds));
  await db.delete(pileActualSteps).where(inArray(pileActualSteps.checklistPileId, checklistPileIds));
  await db.delete(pilingChecklistPiles).where(inArray(pilingChecklistPiles.id, checklistPileIds));
}

// ─── Checklist Personnel ──────────────────────────────────────────────────────

/**
 * Replace all personnel assignments for a checklist day.
 */
export async function setChecklistPersonnel(
  checklistId: string,
  entries: NewPilingChecklistPersonnel[],
  dbHandle?: Db | Tx,
): Promise<void> {
  const db = dbHandle ?? (await initDb());
  await db
    .delete(pilingChecklistPersonnel)
    .where(eq(pilingChecklistPersonnel.checklistId, checklistId));
  if (entries.length) {
    await db.insert(pilingChecklistPersonnel).values(entries);
  }
}

/**
 * Get all personnel ids assigned to a checklist.
 */
export async function getChecklistPersonnelIds(
  checklistId: string,
): Promise<string[]> {
  const db = await initDb();
  const rows = await db
    .select({ personnelId: pilingChecklistPersonnel.personnelId })
    .from(pilingChecklistPersonnel)
    .where(eq(pilingChecklistPersonnel.checklistId, checklistId))
    .all();
  return rows.map((r) => r.personnelId);
}

/**
 * Get all role-assignment rows for a checklist (role/machineId/shiftSlot
 * included) — used to rebuild a ChecklistPersonnelAssignment-shaped draft
 * when reopening an existing plan for edit (Phase 3).
 */
export async function getChecklistPersonnel(
  checklistId: string,
): Promise<PilingChecklistPersonnel[]> {
  const db = await initDb();
  return db
    .select()
    .from(pilingChecklistPersonnel)
    .where(eq(pilingChecklistPersonnel.checklistId, checklistId))
    .all();
}